### ISSUE TITLE
Addons problem

### ISSUE THREAD

**Issue by Romaysa** [NikosAlexandris/i.landsat8.swlst#3]
Sir,
i wanted to instal the i.landsat8.swlst 

1. (

- Wed Jul 12 08:30:17 2017)                                                      
- 2. g.extension extension=i.landsat8.swlst operation=add                            
- 3. WARNING: Extension <i.landsat8.swlst> already installed. Re-installing...
- 4. Downloading precompiled GRASS Addons <i.landsat8.swlst>...
- 5. Updating addons metadata file...
- 6. Installation of <i.landsat8.swlst> successfully finished
- 7. (Wed Jul 12 08:30:51 2017) Command finished (33 sec)      

and i am not able to open it in ad dons GUI its not available in  modules                      
- 
!

1. [picture one](https://user-images.githubusercontent.com/26703637/28106819-51c367c4-66dd-11e7-999b-09914b3bc800.png)
2. ![picture two](https://user-images.githubusercontent.com/26703637/28106917-98e20d36-66dd-11e7-9fcc-a1211348457b.png)

in picture two in the manage extensions i can see the addons .

my grass version is 7.2.1

Regards

**Comment by NikosAlexandris** [comment]
Honestly, I have not tried to use the module from within the GUI. I will try to do that. For the moment, could you please try to use it from the command line? Try the minimal example(s), as described in the main page [https://github.com/NikosAlexandris/i.landsat8.swlst](https://github.com/NikosAlexandris/i.landsat8.swlst).

**Comment by elze-s** [comment]
Firstly, thanks a millions for this nice algorithm. Further, I wanted to ask, if it is possible to apply the algorithm to a space-time landsat raster. 
Kind regards.
