### ISSUE TITLE
FROM-GLC

### ISSUE THREAD

**Issue by Romaysa** [NikosAlexandris/i.landsat8.swlst#4]
Sir,
how to download data from FROM-GLC for land cover parameters, i wanted to download the data i got this massage for the place i want to download.
Forbidden

- [ ] You don't have permission to access /data/Fengduole/Simulation/2010/Geotiff/N31E065_2010_landcover.tif on this server.
- [ ] 
- [ ] Apache/2.2.22 (Ubuntu) Server at data.ess.tsinghua.edu.cn Port 80

Regards

**Comment by NikosAlexandris** [comment]
Visit the [http://data.ess.tsinghua.edu.cn/](http://data.ess.tsinghua.edu.cn/) page. Then, go through the products and understand which one is for you. I think, last time, I downloaded products from [http://data.ess.tsinghua.edu.cn/landsat_pathList_fromglcagg_0_1.html](http://data.ess.tsinghua.edu.cn/landsat_pathList_fromglcagg_0_1.html).

**Comment by NikosAlexandris** [comment]
About accessing issues, perhaps you might need to check your firewall settings or consult your admin(s), if you are behind a corporate firewall. Good luck.
