### ISSUE TITLE
Application on Space-Time-Raster

### ISSUE THREAD

**Issue by elze-s** [NikosAlexandris/i.landsat8.swlst#5]
Firstly, thanks a millions for this nice algorithm. Further, I wanted to ask, if it is possible to apply the algorithm to a space-time landsat raster.
Kind regards.

**Comment by NikosAlexandris** [comment]
You can use the algorithm for single image acquisitions (that is for each image separately) that built a time series. Then (re-)built a time series with the Land Surface Temperature images.
