### ISSUE TITLE
No raster created

### ISSUE THREAD

**Issue by elze-s** [NikosAlexandris/i.landsat8.swlst#6]
Hello, like the title says, I got no raster output unfortunately. Only some files in cell_misc/lst/. Do I miss a step? Thanks for your help!
Kind regards, Sebastian

**Comment by NikosAlexandris** [comment]
Dear @elze-s, I guess you are past the problem, since you closed the issue. If ever needed, for future reference, please refer to the repository in gitlab: https://gitlab.com/NikosAlexandris/i.landsat8.swlst.
Thank you.
